services:
  - type: web
    name: quantum-walk-explorer
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn webapp:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
